---
- name: Install Docker
  hosts: all
  become: yes
  tasks:
    - name: Install Docker dependencies
      apt:
        update_cache: true
        pkg:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
    - name: Add Docker’s official GPG key
      shell: curl -fsSL https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg --batch --yes
    - name: Set up stable repository
      shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{ ansible_distribution|lower }} $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    - name: Install Docker
      apt:
        update_cache: true
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
